### ISSUE TITLE
GRPException bug again!

### ISSUE THREAD

**Issue by ashinpan** [pnprog/goreviewpartner#102]
The GRPException bug still lingers. 

I tried to analyze a game between Ke Jie and Shin Jiseo, which has 162 moves, using 10k playouts per move with LZ net 202. The analyzed range of moves is 152-162. And I made sure that "Stop the analysis if the bot resigns" checkbox is NOT checked. 

But the analysis stopped before completion; the terminal output is as follows:

==============
move 152
leela Zero play white
Number of alternative sequences: 2
==== no more sequences =====
==== creating heat map =====
For this position, Leela Zero would play: S9
Analysis for this move is completed
now asking Leela Zero to play the game move: white at S9

==============
move 153
leela Zero play black
Number of alternative sequences: 6
==== no more sequences =====
==== creating heat map =====
For this position, Leela Zero would play: RESIGN
Analysis for this move is completed
now asking Leela Zero to play the game move: black at S11

==============
move 154
leela Zero play white
Number of alternative sequences: 17
==== no more sequences =====
==== creating heat map =====
For this position, Leela Zero would play: M4
Analysis for this move is completed
now asking Leela Zero to play the game move: white at M4

==============
move 155
leela Zero play black
Number of alternative sequences: 26
==== no more sequences =====
==== creating heat map =====
For this position, Leela Zero would play: RESIGN
Analysis for this move is completed
now asking Leela Zero to play the game move: black at L4

==============
move 156
leela Zero play white
Number of alternative sequences: 13
converting GRPException error message from unicode to str
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pan/devel-goreview/toolbox.py", line 1067, in run_all_analysis
    answer=self.run_analysis(self.current_move)
  File "/home/pan/devel-goreview/leela_zero_analysis.py", line 97, in run_analysis
    i,j=gtp2ij(one_deep_move)
  File "/home/pan/devel-goreview/toolbox.py", line 123, in gtp2ij
    raise GRPException("Cannot convert GTP coordinates "+str(move)+" to grid coordinates!")
GRPException: Cannot convert GTP coordinates pass to grid coordinates!

**Comment by pnprog** [comment]
Hi!

Sorry, problem with same root cause as the previous issue :(
Should be ok now. (i hope!)

**Comment by ashinpan** [comment]
Thanks, for it seems OK now, as you said. I am closing the issue.
