### ISSUE TITLE
It's annoying to play a stonesound mixed with  a beep

### ISSUE THREAD

**Issue by jun63cn** [pnprog/goreviewpartner#104]
With latest commit I using a stonesound file It happens. How to disable it?

**Comment by pnprog** [comment]
Hi!

How can you hear a sound stone? I did not provide any sound file. (I added the feature but it should be disabled)

Where/when do you hear that sound?

**Comment by pnprog** [comment]
I think I find it, it's a warning sound ("bell") from the terminal due to some error.

I just pushed a fix, can you try again and let me know?

**Comment by jun63cn** [comment]
It's OK now.  Thank you very much!
