### ISSUE TITLE
Feature request: Setting to abort analysis when bot would resign

### ISSUE THREAD

**Issue by fishcu** [pnprog/goreviewpartner#11]
It would be useful to have a checkbox in the settings that allows GRP to stop the analysis of a game once the bot resigns. I'm sure I'm not the only Go player that is guilty of continuing a game long after the result was clear. ;)

**Comment by pnprog** [comment]
Good suggestion! I will implement that!

**Comment by pnprog** [comment]
@fishcu ,

I just added the feature, you can have a try!

**Comment by fishcu** [comment]
Great, testing now!

**Comment by fishcu** [comment]
Works!
