### ISSUE TITLE
Feature Request: Batch mode

### ISSUE THREAD

**Issue by bjordan2010** [pnprog/goreviewpartner#111]
Process all SGF files in a folder.

**Comment by pnprog** [comment]
You can use goreviewpartner in command line for batch processing:

`python leela_analysis.py *.sgf`

[See also documentation](http://yuntingdian.com/goreviewpartner/grp-documentation/doc.htm#advanced-uses)

**Comment by bjordan2010** [comment]
I hadn't seen this, thanks for pointing it out.
