### ISSUE TITLE
New release (the last one is after v0.14.2)

### ISSUE THREAD

**Issue by tomasz-warniello** [pnprog/goreviewpartner#118]
Would it be easy for you to issue a new release?

**Comment by pliuphys** [comment]
I just downloaded the windows no bot package. The file name is goreviewpartner-v0.15.zip and has files modified this month. Is this a new version?

**Comment by tomasz-warniello** [comment]
I thought the releases would be here too https://github.com/pnprog/goreviewpartner/releases

**Comment by pnprog** [comment]
Hi @tomasz-warniello @pliuphys 

Yes, v0.15 is the latest version, I just forgot to put a tag on the gihub to make that release "official" (I will do that once I get home).

Same as last time, there should be a number of bugs that I did not notice, and that I fill fix quickly (v15.1) before starting adding new features.

Sorry about that, all of this has been rushed a little bit.

**Comment by tomasz-warniello** [comment]
I'm closing this request then. Thanks.
