### ISSUE TITLE
"Graphs" button not appearing

### ISSUE THREAD

**Issue by apetresc** [pnprog/goreviewpartner#12]
I've generated an .rsgf file using Leela 0.11.0 OpenCL. Everything about the analysis looks reasonable, except that there's no "Graphs" button to show the winrate graphs. There's nothing in stdout that would indicate any sort of problem.

![](https://s3.amazonaws.com/apetresc-screenshot/2017-12-21-23.37.31.png)

This is on Windows 10, GRP 0.9.

Is there some setting I need to enable for this?

**Comment by Cin316** [comment]
I'm having the same issue on macOS 10.12.6 with GRP 0.9.  Maybe this is new bug with 0.9?

**Comment by Cin316** [comment]
Hmmm... It looks like the graphs only work if you do analysis on both players, black and white.  Does that fix your problem?

This should be noted in the documentation.

**Comment by apetresc** [comment]
Ah, I bet you’re right - it makes sense too (although a graph at
half-density is also conceivable). I’ll give it a try tonight.

**Comment by pnprog** [comment]
Yes, analysis for both colors must be performed to get a graph, but only for the comparison graphs (comparison between bot's best move and player's move). At least the win rate graph should be available. I will investigate this right away.

**Comment by pnprog** [comment]
@apetresc , @Cin316 ,

I had a look at my code, ad it appears I was completely wrong for this!

I just fixed that, now it's possible to display the normal win rate even when one of the two colors is not part of the analysis.

The result looks like this:
![capture du 2018-01-13 11-11-15](https://user-images.githubusercontent.com/25114663/34902277-3382b7f8-f853-11e7-88c3-7f3a93e8f7f2.png)
