### ISSUE TITLE
UI Suggestion: Make bot dropdown wider in toolbox.py

### ISSUE THREAD

**Issue by bjordan2010** [pnprog/goreviewpartner#123]
I'm a Java developer so 1) forgive me if there is a better way and 2) it took me quite a while to figure this out but I made this change in my fork of the code in toolbox.py.

		botOptionMenu = apply(OptionMenu,(self, self.bot_selection)+tuple(bot_names))
		botOptionMenu.config(width=20)
		botOptionMenu.grid(row=row,column=2,sticky=W)

Instead of 

apply(OptionMenu,(self,self.bot_selection)+tuple(bot_names)).grid(row=row,column=2,sticky=W)

With the latter code the box was barely over a 1 cm wide.  This is around 5 so the first name is readable.  It is also closer to the size of the variation dropdown.

**Comment by pnprog** [comment]
Hi @bjordan2010 

If you have made a fork with your change; please make a pull request, I will gladly accept it :)

**Comment by tomasz-warniello** [comment]
Is this one not closed by #125 ?
