### ISSUE TITLE
Error at end of analysis

### ISSUE THREAD

**Issue by abhuva** [pnprog/goreviewpartner#13]
Hello, i get the following Error Message in the console after analyzing a game:

Adding sequence starting from D6
==== no more sequences =====
Creating the influence map
Saving RSGF file C:/Users/Marc Bielert/Desktop/Go/SGF-My Games for Review/180114_1.rsgf
now asking Leela to play the game move: black at d7
Analysis for this move is completed
120 move(s) analysed in 2610.2 secondes => 22.7 s/m

move 121/121 leela play black
Number of alternative sequences: 2
Adding sequence starting from E6
20.38%/79.62% releasing lock
leaving thread
120 move(s) analysed in 2616.8 secondes => 22.8 s/m
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1532, in __call__
  File "Tkinter.pyc", line 583, in callit
  File "toolbox.pyc", line 658, in follow_analysis
error: release unlocked lock

The thing is: that the review file gets created and is readable. So i am not sure whats happening and if i can just ignore it.

**Comment by pnprog** [comment]
Hi @abhuva !
Can you share the SGF file with me?

**Comment by abhuva** [comment]
[180114_1.zip](https://github.com/pnprog/goreviewpartner/files/1629957/180114_1.zip)

Sure, its a game from IGS (Pandanet), tried it with 2 others (also from my game-history on pandanet) and had the same issue. But the resulting rsgf files do work and the analysis is working. I just have to close the progress bar by hand as its not finishing (remains always with a couple seconds left).

**Comment by pnprog** [comment]
In fact, I fixed this bug in a commit one week ago (5a724088aac8804c4c438f91c62d96195f05f00f) hopefully this should be working fine now (your SGF works for me now, but does not work on the previous v0.9). You can try from the sources or wait for me to release a version 0.10 this month.

Thanks for reporting the bug !
