### ISSUE TITLE
Crash when cancelling review

### ISSUE THREAD

**Issue by fishcu** [pnprog/goreviewpartner#16]
When cancelling an ongoing review (I tested with Leela), the program crashes:

```
move 2/336 leela play black
going deeper for first line of play ( 1 )
going deeper for first line of play ( 2 )
going deeper for first line of play ( 3 )
going deeper for first line of play ( 4 )
RunAnalysis beeing closed
killing Leela
going deeper for first line of play ( 5 )
leaving consume_stderr thread
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ibd/dev/forked/goreviewpartner/toolbox.py", line 687, in run_all_analysis
    self.run_analysis(self.current_move)
  File "leela_analysis.py", line 76, in run_analysis
    answer=leela.play_white()
  File "/home/ibd/dev/forked/goreviewpartner/gtp.py", line 138, in play_white
    raise GtpException("GtpException in genmove_white()\nanswer='"+answer+"'\n"+str(e))
GtpException: GtpException in genmove_white()
answer=''
list index out of range

RunAnalysis closed
```

**Comment by pnprog** [comment]
Hi!

In fact, this should be  without consequence. There is no easy way to tell a GTP program to stop thinking and quit, so GRP just forcefully terminates the process, and the thread that manages it. The important thing is to be sure to have Leela/Ray/AQ release the resources they use. Normally, the rest of GRP should still be running without issue, and you can start a new analysis right away.

IIRC, in the previous versions, I had it silently crash (`try: ... except: pass`) but if the thread fails for another issue, it's hard to know what happened. so now I prefer to let it crash in a very "verbose" way.

**Comment by fishcu** [comment]
That makes sense. Still, this is basically an unhandled exception. I guess it makes no difference in practice.
