### ISSUE TITLE
Leela analysis reports low B winrate, but B actually wins -- self play confirms

### ISSUE THREAD

**Issue by fishcu** [pnprog/goreviewpartner#18]
I've seen this issue in more than one game. During the analysis with Leela, a very low winrate is shown for black (B), when actually B is winning. When looking at the .rsgf afterwards, and letting Leela self play (after "open position"), you can confirm that actually white (W) resigns instead of black.

I suspect that this may be a bug with komi, that is, the correct komi is not forwarded to leela. In the example game, white would win with regular komi, but not with the game komi (0.5).

I have attached a sample .sgf, the resulting .rsgf, and a screenshot showing the problem.

[eggless-ibd.rsgf.zip](https://github.com/pnprog/goreviewpartner/files/1704297/eggless-ibd.rsgf.zip)
[eggless-ibd.sgf.zip](https://github.com/pnprog/goreviewpartner/files/1704298/eggless-ibd.sgf.zip)
![wrong_counting](https://user-images.githubusercontent.com/25356186/35934421-da2f8d8a-0c3d-11e8-8814-219be0dfe0ad.png)

**Comment by fishcu** [comment]
Additionally, I attach this screenshot from the beginning of the analysis, where the GUI shows komi "0.5". So, I cannot be sure if there is a bug with the komi, but I'm still very suspicious that it is related to that.

![eggless-ibd](https://user-images.githubusercontent.com/25356186/35934520-222269be-0c3e-11e8-97f6-f50b5ebfa2e9.png)

**Comment by pnprog** [comment]
Hum, I can't reproduce this issue with Leela and your sgf file.

When implementing the live analysis feature, I encountered and fixed plenty of bugs, maybe I fixed that one as well. Can you try again with latest sources?

**Comment by fishcu** [comment]
I re-tried with the latest commit and indeed the issue appears to be fixed!
