### ISSUE TITLE
Missing invertedmousewheel option causes traceback

### ISSUE THREAD

**Issue by bitlux** [pnprog/goreviewpartner#22]
This is happening on macOS 10.13.3, python 2.7.10

`Initializing GRP setting interface`
`Exception in Tkinter callback`
`Traceback (most recent call last):`
`  File "/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1541, in __call__`
`    return self.func(*args)`
`  File "main.py", line 126, in launch_settings`
`    settings.OpenSettings(app)`
`  File "/Users/XXX/Desktop/goreviewpartner-master/settings.py", line 155, in __init__`
`    self.display_settings()`
`  File "/Users/XXX/Desktop/goreviewpartner-master/settings.py", line 22, in display_settings`
`    new_settings=settings_dict[key](self.setting_frame)`
`  File "/Users/XXX/Desktop/goreviewpartner-master/settings.py", line 109, in display_GRP_settings`
`    InvertedMouseWheel = BooleanVar(value=Config.getboolean('Review', 'InvertedMouseWheel'))`
`  File` `"/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 368, in getboolean`
`    v = self.get(section, option)`
`  File` `"/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 618, in get`
`    raise NoOptionError(option, section)`
`NoOptionError: No option 'invertedmousewheel' in section: 'Review'`

**Comment by pnprog** [comment]
Thanks!
