### ISSUE TITLE
AQ has a problem with the win probability 

### ISSUE THREAD

**Issue by 20010723** [pnprog/goreviewpartner#26]
Thank you for creating this software.It was a great help to me.
In AQ，the win probability is value，not roll.
You can try to analyzing a handicap game.

**Comment by pnprog** [comment]
Hi!

For the win probability, I use the calculation as described in this thread: https://github.com/ymgaq/AQ/issues/20

It is a function of both value, roll, and the move number:
```
	def win_rate(self,current_move,value,roll):
		return roll
		#see discussion at https://github.com/ymgaq/AQ/issues/20
		if current_move<=160:
			lmbd=0.8
		else:
			lmbd=0.8-min(0.3,max(0.0,(current_move-160)/600))
		rate=lmbd*value+(1-lmbd)*roll
		return rate
```

**Comment by pnprog** [comment]
Also, be aware that currently, AQ (and Ray) does not calculate the score in handicap game the same way as most other bots. So in handicap game, the win rate calculation may be plain wrong depending of the rule set you are considering.

This is discussed there: https://github.com/ymgaq/AQ/issues/84

I plan to add a warning for this issue until it is fixed by AQ/Ray

**Comment by 20010723** [comment]
ymgaq / AQ＃84
I usually refer 'value' as winning rate for analyzing game, so you can plot the chart using 'value'.If you absolutely want to calculate the internal proportion, use the following formula:lambda * value + (1-lambda) * rollout_ratewhere lambda = 0.8 - min(0.3, max(0.0, (move_cnt - 160) / 600)).
--
I am a professional player.In my experience, choosing only value is enough.
Thank you for constantly updated ~ ~

**Comment by pnprog** [comment]
Hi!

I wen't ahead and implement graphs (and delta graphs) for all  metrics for AQ (so win rate, value network and monte carlo):

![all](https://user-images.githubusercontent.com/25114663/37096304-361a5564-2253-11e8-8d54-77e312104012.png)

As you mentioned, win rate and value network are very very similar:

![3_graphs](https://user-images.githubusercontent.com/25114663/37096348-52ec4ecc-2253-11e8-845a-60a8863623a6.png)

There may be some edge cases (maybe high handicap games) where the monte carlo could be more accurate, it it's good to have it around just in case.

> I am a professional player.

This is so cool! Please let me know if you have idea for improving GRP :)
