### ISSUE TITLE
Include AQ in addition to Leela and RayN?

### ISSUE THREAD

**Issue by Razza99** [pnprog/goreviewpartner#3]
https://github.com/ymgaq/AQ/releases

Recently released, and has been doing quite well on cgos (above Leela, RayN and some versions of Zen).
http://www.yss-aya.com/cgos/19x19/standings.html

I've heard it deals better with life and death than Leela, though haven't tested enough to confirm this. 

Love your work - thanks for a very useful program!

edit: just saw your post on the AQ github. Looks like it's already in the works. Cheers!

**Comment by pnprog** [comment]
Haha, yes I am working on it at the moment.

**Comment by pnprog** [comment]
I just publish v0.9, that includes support for AQ.
