### ISSUE TITLE
Proposal: new interface for dual_view similar to AlphaGo Teach

### ISSUE THREAD

**Issue by liverex** [pnprog/goreviewpartner#31]
Thanks a lot for the powerful tool.
As we know, the current dual_view is using the "ABCDEFG..." to indicate different variations.
Shall we have a new interface/setting which marks the different variations with the winrate/visits/colors similar to AlphaGo Teach website?
Another review tool named Lizzie is working on this and become quite popular.

**Comment by liverex** [comment]
Thanks a lot!

**Comment by pnprog** [comment]
Honestly, the result is not as beautiful as in @CamWagner 's Lizzie program. Tkinter, the graphical framework used by GRP cannot deal with transparency, so trying to display a color gradient on the "wood looking" goban would give an awkward result.

In the future, like for versions 2.x, I would like to move to another graphical framework.
