### ISSUE TITLE
SDF file analysis greyed out

### ISSUE THREAD

**Issue by bjordan2010** [pnprog/goreviewpartner#32]
When I run python main.py on Mac OSX 10.12.6 the SDF options are greyed out.  What am I missing?

**Comment by bjordan2010** [comment]
Nevermind I was attempting to use the Leela GUI app instead of the engine.

**Comment by pnprog** [comment]
Hi! Those options are greyed when not bot's command line as been set in the setting panel.
So if not bot is available, everything related to analysis is disabled, only reviewing RSGF file is enabled.
