### ISSUE TITLE
Feature request: Shutdown computer after analysis.

### ISSUE THREAD

**Issue by pondturtle** [pnprog/goreviewpartner#36]
I usually leave for work/school and give LZ 2+ hours to crunch the game. I jsut like to be sure :-). Can we get "shut down after analysis is done and rsgf is saved" feature? Thanks

**Comment by pnprog** [comment]
Hi!

I thing turning of the computer is out of the scope of GRP, there is probably no standard/cross platform way to do that in python, and in some case, it will require admin level.

But what you can do is use the scripting feature of GRP. A script like this for linux would do the job (you need to run GRP from the python source):

```
#!/bin/bash
python leela_zero_analysis.py my_game.sgf
poweroff
```
Depending on you system, this could require to be run as root.

For windows, you apparently can use the [shutdown](https://www.tutorialspoint.com/batch_script/batch_script_shutdown.htm) command and run this from a **.bat** file.

```
python leela_zero_analysis.py my_game1.sgf my_game2.sgf my_game3.sgf
shutdown
```

Check out the examples on how to use the command line at the very end of [the documentation](http://ns1297.imingo.net/grp-documentation/doc.htm)
