### ISSUE TITLE
Multi-review

### ISSUE THREAD

**Issue by kris-computer-go** [pnprog/goreviewpartner#4]
Thank you for adding support of AQ in current ver.
It would be nice to add an option for multi-review, I mean choosing not 1 but more bots at the same time and creating one rsgf file for it.

**Comment by pnprog** [comment]
Hi @kris-computer-go ,

This would imply a lot heavy of changes to GoReviewPartner, both on the analysis part and the GUI part. I am not sure many users would need this as well.

I think one easier way to achieve that would be a small script that "merge" 2 or more RSGF files into a big one.

GoReviewPartner can now be ran from a script, so it would be possible to launch a script that runs the several analysis one by one (so one analysis per bot) then merge all resulting RSGF files into a big one.
