### ISSUE TITLE
AQ(CPU-only) not working

### ISSUE THREAD

**Issue by Wizard106** [pnprog/goreviewpartner#49]
It gives me the error:

> AQ did not identified itself as expected
> 'AQ' != ''

This happens both with the version directly downloaded with goreviewpartner and also the one from https://github.com/ymgaq/AQ/releases

**Comment by pnprog** [comment]
Hi!

Thanks for reporting the issue. 

This seems more like a problem with running AQ on your computer. What happens when you run AQ directly by double clicking on **AQ.exe** ?

**Comment by Wizard106** [comment]
Two system errors pop up. First is:

> The code execution cannot proceed because MSVCP140.dll was not found. Reinstalling the program may mix this problem.

And second is:

> The code execution cannot proceed because VCRUNTIME140.dll was not found. Reinstalling the program may mix this problem.

Did some research and downloaded the Visual C++ Redistributable for Visual Studio 2015 now it works fine, thanks for the help!

**Comment by pnprog** [comment]
Good to know! Let me know if you have other issues running GRP.
