### ISSUE TITLE
Completed Chinese support

### ISSUE THREAD

**Issue by jiangwuyou** [pnprog/goreviewpartner#50]
Need to commit three modified files.

**Comment by jiangwuyou** [comment]
Submitted at https://gist.github.com/jiangwuyou .

**Comment by jiangwuyou** [comment]
Found a bug in toolbox.py

+            if lang='zh'
+                    translation=translation.decode("GBK")
+            if lang='kr'
+                    translation=translation.decode("korean")   //Guess. No Test for Korean

**Comment by pnprog** [comment]
Hi @jiangwuyou !

As I understand, you are working on a Chinese translation for GRP?

May I suggest to use Unicode (**UTF**) encoding for the **zh.po** file (instead of **GBK**) ? Unicode works fine for all language (including Korean and Chinese).

If this is ok for you, I can create an empty **zh.po** file and modify GRP to use it. Then I can give you access to update this file with Chinese translation.

**Comment by jiangwuyou** [comment]
Dear Pnprog,

Yeah. I'm using Chinese.

 >May I suggest to use Unicode (*UTF*) encoding for the *zh.po* file 
(instead of *GBK*) ? Unicode works fine for all language (including 
Korean and Chinese).
Yeah. I tried the solution also, which use UTF-8 to store zh.po file, 
but I met many key errors so that I have to add many encode/decode for 
your toolkit.py and aianalisys.py in test period. When your 
GopreviewPartner run, the Chinese string in memory are stored as 
ASCII(or GBK?) format so that test statement of "print aString" will 
show abnormal, and all Chinese key/value in dictionary are showed 
abnomal too.

If I used GBK format to store zh.po file, then all Chinese string will 
show normal for "print aString" statement. Some encode/decode function 
will be removed from those (Bot).py file. I have released a temporary 
GoReviewPartner.exe which is packed by pyInstaller. If possible, I wish 
to commit those modifciaton or email you a zip file which contains all 
modified files.

With best regards,

Jiangwuyou

**Comment by jiangwuyou** [comment]
For Chinese or Korean, the trouble is to debug many key errors. According to my test, GBK tranaltion file,  not UTF-8 tranaltion file, needn't too much modification for your raw source code.

**Comment by pnprog** [comment]
The Korean translation is working well. French and Dutch translations are also based on UTF-8 and are working well. So it would be surprising is the Chinese/UTF translation is not working. Maybe an issue with **pyinstaller** ?

For test purpose can you share a **zh.po** file (UTF or GBK) with me, so that I can check everything is working? Not necessarily a complete translation, it is just for testing.

Thanks!

**Comment by jiangwuyou** [comment]
I found an issue:
For SGF file, it can be GBK or UTF-8 file, so it will failed to open some SGF file.


	try:

		if lang=="zh":    
			txt=txt.decode("GBK")
		elif lang=="kr":
			txt=txt.decode("korean")

	except UnicodeDecodeError:
			txt=txt.decode("utf-8")

	return txt

**Comment by jiangwuyou** [comment]
In my test environment of Visual Studio witout code modification, a UTF zh.po will show normal, but your key/value map will throw Key error since it store translation as ASCII code.

A GBK zh.po will show abnormal so need to translate first.
 
>For test purpose can you share a zh.po file (UTF or GBK) with me, so that I can check everything is working? 
I upload four file for test at https://gist.github.com/jiangwuyou/6c901e71ff380ba7ede8e2805a794977. With a translate function, it can run for GUI,key/value dict, SGF palyer information.

**Comment by jiangwuyou** [comment]
BTW, I'm using Python2.7, and used 
import sys, os
reload(sys)
sys.setdefaultencoding('utf-8')

**Comment by pnprog** [comment]
Hi!

First of all, let's me thanks you for the translation, I really appreciate the effort!

I integrated the Chinese translation to GRP. I used your **zh.po In GBK** file, but apparently, its encoding was UTF-8, not GBK (I don't know about the encoding of your other file **zh.po in UTF-8**).

As you mentioned, there was plenty of display issues with the UTF-8 translation. I am not sure why it's not working out of the box. So I made some change in the code to fix all of that, and I hope it's now working, and will be working for other translations as well:

![chinese](https://user-images.githubusercontent.com/25114663/39805035-437f6aba-53a8-11e8-897e-c71de0bc7aa5.png)

Then, I checked your SGF files, and yes, GRP had issues working with those files with different encoding than UTF-8, so I completely reworked the way SGF files opened: now, the encoding is tested at opening, and then the SGF is converted to UTF-8 encoding all the time. I tested this method with several encoding (BIG5, GB18030, SHIFT_JIS) and it's working fine (analysis of sgf, review of rsgf, conversion to sgf).

This is a big improvement :)

**Comment by jiangwuyou** [comment]
>I integrated the Chinese translation to GRP. I used your zh.po In GBK file, but apparently, 
>its encoding was UTF-8, not GBK (I don't know about the encoding of your other file zh.po in UTF-8).
The raw file is encoded correctly, but I don't know whether gist will store correctly since I use Paste to upload the content.

>So I made some change in the code to fix all of that, and I hope it's now working,
>and will be working for other translations as well:
Yeah. Your pasted GUI show normally:) But I will check whether the key/value issue exists still. I will compare the different code solution between you and me.

**Comment by pnprog** [comment]
> The raw file is encoded correctly, but I don't know whether gist will store correctly since I use Paste to upload the content.

Maybe your web browser directly converted to UTF-8, because github web pages are all in UTF-8
By the way, if it ok for you, I would like to give you write access to this project, so that you can directly update the Chinese translation if you think it is necessary. Is that ok for you?

> But I will check whether the key/value issue exists still. I will compare the different code solution between you and me.

One important change I made is in the translation function **_()**
 
```
def _(txt=None):
 	global translations
 	if not translations:
		#return txt
		return unicode(txt)
 	if translations.has_key(txt):
 		return translations[txt]
	#return txt
	return unicode(txt)
```
I make sure all the translation strings are of type unicode now.

Let me know if you see any error elsewhere.

**Comment by jiangwuyou** [comment]
Yeah. I checked that code:)

I found that your zh.po is encoded in GBK, but I have tried both of  GBK and UTF-8, No issue:)

I closed that thread:)
