### ISSUE TITLE
command line error

### ISSUE THREAD

**Issue by wjx0912** [pnprog/goreviewpartner#51]
hi, pnprog, 

i run the program with command line(can't use gui),

$ python2 main.py --no-gui
STDIN encoding: UTF-8
STDOUT encoding: UTF-8
STDERR encoding: UTF-8
File system encoding: UTF-8
GRP path: /home/wyt/weiqi/goreviewpartner-0.11.2_python2_elf
Config file: /home/wyt/weiqi/goreviewpartner-0.11.2_python2_elf/config.ini
Reading language setting from config file
lang=en
Could not import the WX GUI library, please double check it is installed:
No module named wx
=> Falling back to tkFileDialog
Checking availability of config file
Traceback (most recent call last):
  File "main.py", line 144, in <module>
    app = Application()
  File "/home/wyt/weiqi/goreviewpartner-0.11.2_python2_elf/toolbox.py", line 1827, in __init__
    Tk.__init__(self)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1822, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":0.0"

----------------------------------------------

in log, i find "No module named wx", can you fix it? thanks

i try pip2 install wxPython, it failed on the just enviroment.

wait your reply, 
best regards~

**Comment by pnprog** [comment]
Hi!

`_tkinter.TclError: couldn't connect to display ":0.0"`

Apparently, you are running GRP on a system without display.

I see, it should be possible modify GRP so to initialize **tkinter** only when the GUI is launched, to make it possible to run GRP with **--no-gui** without having **tkinter** (or **wxpython**) installed. I will look into it.

By the way, **main.py** cannot be ran directly in command line. Please check this: [Advanced uses](http://yuntingdian.com/goreviewpartner/grp-documentation/doc.htm#advanced-uses)

**Comment by wjx0912** [comment]
@pnprog thank you, i'll test it.
