### ISSUE TITLE
Invalid mode ('rwb')

### ISSUE THREAD

**Issue by jiangwuyou** [pnprog/goreviewpartner#52]
It's strange
>	Config.readfp(open(config_file))
	Config.readfp(codecs.open(config_file,"rw","utf-8"))
My test will show
GRP path: D:\LeeLa\goreviewpartner
Config file: D:\LeeLa\goreviewpartner\config.ini
Checking availability of config file
ERROR: Could not open the config file of Go Review Partner
Invalid mode ('rwb')

So I used
	Config.readfp(codecs.open(config_file,"r","utf-8"))
for test

**Comment by xiaozhezhang** [comment]
The same problem occurs here.

STDIN encoding: None
STDOUT encoding: UTF-8
STDERR encoding: UTF-8
File system encoding: mbcs
GRP path: D:\goreviewpartner-master
Config file: D:\goreviewpartner-master\config.ini
Checking availability of config file
ERROR: Could not open the config file of Go Review Partner
Invalid mode ('rwb')

**Comment by jiangwuyou** [comment]
Yeah. Use my upper code can read/write normally.

**Comment by pnprog** [comment]
yeah, I messed up in the last update, I will fix that right now!

**Comment by pnprog** [comment]
Just fixed it.

I plan to re-wrap these **Config.readfp**, **ConfigParser.ConfigParser**, **Config.read**, **Config.get**, **Confit.set** and **Config.write** into one nice and clean class. At the moment, it is just a very ugly code.
