### ISSUE TITLE
ValueError when running a SGF file analysis

### ISSUE THREAD

**Issue by miguno** [pnprog/goreviewpartner#56]
# Environment

- Platform: Windows 10
- goreviewpartner version: latest `master` (https://github.com/pnprog/goreviewpartner/commit/1d37926eec0b4a63749a3335d76627c12a488a1e)
- SGF file: [2018-05-10T16_25_29.910Z.zip](https://github.com/pnprog/goreviewpartner/files/1992465/2018-05-10T16_25_29.910Z.zip) (created by leela-zero during training run via `autogtp.exe`)

# How to reproduce

- Launch goreviewpartner
- Click _Run a SGF file analysis_
- Select the attached SGF file.

It seems to be an problem caused by leela-zero's SGF files, as other SGF files (e.g. http://www.alphago-games.com/static/games/agzero_vs_agmaster/Game_001.sgf) work properly.

Here's the source of the problematic SGF file:

```
(;FF[4]GM[1]

AP[LeelaWatcher 1.0]

GN[Leela vs. Leela]
EV[Leela Zero Self Training]
RE[?]
DT[2018-05-10T16:19:34.094Z] PC[Location Unknown]
GC[]

PW[Leela] WR[?]
PB[Leela] BR[?]

HA[0] KM[7.5] SZ[19]
RU[Japanese]

;B[pp];W[pd];B[dp];W[cd];B[ec];W[dc];B[ed];W[cf];B[md];W[pg];B[pc];W[qc];B[oc];W[qb];B[of];W[pf];B[od];W[pe];B[jd];W[qq];B[pq];W[qp];B[qn];W[qo];B[po];W[rn];B[qm];W[rm];B[ql];W[cn];B[co];W[dn];B[fq];W[eg];B[dk];W[gn];B[ip];W[fk];B[cl];W[gp];B[fp];W[fo];B[gq];W[bm];B[bo];W[ei];B[bl];W[gc];B[ge];W[on];B[de];W[ce];B[pr];W[rl];B[nm];W[om];B[ol];W[nn];B[qk];W[mq];B[ml];W[ln];B[lp];W[mp];B[mo];W[mm];B[nl];W[lo];B[no];W[mn];B[lq];W[jp];B[mr];W[io];B[hp];W[kp];B[kr];W[he];B[hd];W[gd];B[hf];W[ie];B[id];W[fe];B[gf];W[ff];B[jf];W[ll];B[db];W[fb];B[cc];W[dd];B[eb];W[cb];B[  ])
```

# Error message

After the SGF file was selected in the popup dialogue the console output shows:

```
STDIN encoding: cp437
STDOUT encoding: cp437
STDERR encoding: cp437
File system encoding: mbcs
GRP path: c:\Go\goreviewpartner
Config file: c:\Go\goreviewpartner\config.ini
Checking availability of config file
Reading language setting from config file
lang=en
refreshing
Adding new popup
Totally 1 popups
filename: C:\Go\leelaz\2018-05-10T16_25_29.910Z.sgf
variation changed! Variation 1 (95 moves)
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "main.py", line 89, in launch_analysis
    new_popup=RangeSelector(self.parent,filename,bots=get_available("AnalysisBot"))
  File "c:\Go\goreviewpartner\toolbox.py", line 491, in __init__
    board, unused = sgf_moves.get_setup_and_moves(self.g)
  File "c:\Go\goreviewpartner\gomill\sgf_moves.py", line 57, in get_setup_and_moves
    moves.append((colour, sgf_properties.interpret_go_point(raw, size)))
  File "c:\Go\goreviewpartner\gomill\sgf_properties.py", line 52, in interpret_go_point
    raise ValueError
ValueError
```

At this point the popup window to select the "Bot to use for analysis" etc. is shown, but no `Start` button or similar is visible/clickable:

<img width="264" alt="goreviewpartner-bug" src="https://user-images.githubusercontent.com/294849/39882008-dbe0c724-5482-11e8-8604-3bf3efdec287.png">

When closing the popup window via the `X` button, the following error output is added to the console:

```
Removing popup
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "c:\Go\goreviewpartner\toolbox.py", line 558, in close
    self.parent.remove_popup(self)
  File "c:\Go\goreviewpartner\toolbox.py", line 1769, in remove_popup
    self.popups.remove(popup)
ValueError: list.remove(x): x not in list
```

**Comment by pnprog** [comment]
Hi!

Thanks for the detailed report!

I had a quick check, and apparently, the issue lies at the end of the SGF file:

`;W[fb];B[cc];W[dd];B[eb];W[cb];B[  ])`

The last B ("black plays") property is empty **B[  ]** (two empty space). Apparently, this is a violation of SGF format, and makes [Gomill](https://github.com/mattheww/gomill/) (the sgf parsing library used by GRP) fails to parse this SGF file (I checked using the [sgf checker](https://www.red-bean.com/sgf/sgfc/munch.html)).

As a temporary workaround, simply replace the **B[  ]** by **B[]**

Now, I am curious to know: are all the SGF produced by **autogtp.exe** like this, or is this one somehow special in any way?

I am not sure if one should ask **gomill** project to fix this, or **LeelaZero** project to fix it. Because this is a wrong SGF formatting, **LeelaZero** should fix it. On the other hand, my two other SGF editors can handle this file without problem.

**Comment by miguno** [comment]
I realize that it was actually `autogtp` driven/managed by https://github.com/fsparv/LeelaWatcher, which created the broken sgf file. It looks like this issue here is a duplicate or at least related to https://github.com/fsparv/LeelaWatcher/issues/32.

**Comment by pnprog** [comment]
This sort of cross investigation is fun :)

Let's keep this issue opened, if it does not get fixed, I will patch GRP to deal with it by itself.

**Comment by pnprog** [comment]
Hi!

I finally made a code modification to get rid of this issue. I am closing this now :)

**Comment by miguno** [comment]
Thanks @pnprog !

For reference: https://github.com/pnprog/goreviewpartner/commit/96ea77057c92af4a7ac5eae381975a005f54bb8f
