### ISSUE TITLE
Missed two lines in toolbox.py

### ISSUE THREAD

**Issue by jiangwuyou** [pnprog/goreviewpartner#57]
Line 1986 should be:
		Config=ConfigParser.ConfigParser() //Missed
		Config.read(config_file)  //Missed
		initialdir = Config.get(config[0],config[1])

**Comment by pnprog** [comment]
Thanks for finding this bug, I just pushed a fix: https://github.com/pnprog/goreviewpartner/commit/16a6cfd46221ebef9be6633008b3c14f8d99350c

As I have **wxpython** installed on my computer, I would not have trigger the bug.

I wrapped all those **ConfigParser** calls into a **MyConfig** class that do the heavy job, it will help me simplify several part of the code by providing default values.
