### ISSUE TITLE
Setting stone fuzziness = 0 has no effect?

### ISSUE THREAD

**Issue by fishcu** [pnprog/goreviewpartner#6]
I tried several times to set fuzziness = 0 in the settings, because I prefer it to the default look. I clicked "save settings". However, all the stones still have a random displacement to them.

**Comment by Cin316** [comment]
Yes, I have this same issue.

It seems that no matter what I set the Fuzzy Stones setting to, it still stays around 0.2.  I can't get it to do perfect placement.  The saving of that setting is working, and I can change other settings and see their effects.

It doesn't seem like increasing fuzziness is working either.  It always saves around 0.2.

macOS 10.12.6
Python 2.7.10
Tcl / Tk version 8.5
GCP 0.9

**Comment by pnprog** [comment]
Hi, sorry to come back late on this issue. Do you still have this issue

@fishcu, @Cin316, when you open the config.ini file, what is the value of `fuzzystoneplacement`
Is it set at 0? or still at 0.2 ?

**Comment by fishcu** [comment]
I can confirm that the setting is successfully stored in config.ini. The way it seems is that the setting is not applied properly to the rendering.

**Comment by pnprog** [comment]
@fishcu, @Cin316 ,

Hopefully, I found and fixed this issue. I fact, it was not working for me as well :-/

**Comment by fishcu** [comment]
Works for me with your fix!
