### ISSUE TITLE
this sgf cannot be load

### ISSUE THREAD

**Issue by l1t1** [pnprog/goreviewpartner#64]
http://duiyi.sina.com.cn/cgibo/20184/ls2018qy2-180424h.sgf
the console shows
not a sgf file
ERROR: 不是一个SGF文件F!
(
TE[2

**Comment by l1t1** [comment]
please point out what is not valid and how to fix it

**Comment by l1t1** [comment]
[pk.sgf.txt](https://github.com/pnprog/goreviewpartner/files/2011500/pk.sgf.txt)
this one also has Chinese Character, but can be load and analyze

**Comment by pnprog** [comment]
Hi!

I had a look at the file, and the file does not respect the SGF format. In fact, my two other SGF editors cannot open it as well.

Here is the beginning of the file:
```
(
TE[2018ÀöË®ÇåÔÏ±­ÖÐ¹úÒµÓà¹«¿ªÈü2]
RD[2018-04-24]
PC[ÀöË®ÊÐËÉÑôÏØ]
TM[70]
LT[15]
LC[3]
KO[7.5]
RE[ºÚÊ¤2ÓÖ3/4×Ó]
```
A valid SGF file for Go should start with **;FF[4]GM[1]** as bellow:
```
(;FF[4]GM[1]
TE[2018ÀöË®ÇåÔÏ±­ÖÐ¹úÒµÓà¹«¿ªÈü2]
RD[2018-04-24]
PC[ÀöË®ÊÐËÉÑôÏØ]
TM[70]
LT[15]
LC[3]
KO[7.5]
RE[ºÚÊ¤2ÓÖ3/4×Ó]
```
This can be opened by GRP or gogui.

Although, the encoding is not indicated in the file, so GRP (or gogui) cannot guess that it is chinese Characters, so the player name, event name, and other information won't be displayed properly, but the analysis should be possible.

In comparison, you second file starts like this:
```
(;GM[1]FF[4]
SZ[19]
GN[2018华为手机杯围甲第5轮<张学斌六段＆绝艺解说>]
DT[2018-05-09]
PB[柯洁]
PW[박정환]
BR[P9段]
WR[P9段]
```
You can see the first line is **(;GM[1]FF[4]**
Encoding is missing also, bit this one is UTF-8 encoding, so GRP will open this without issue.

**Comment by pnprog** [comment]
With trial and error, I was able to find the encoding of the first file (GB18030). I modified it as below (added: **;FF[4]GM[1]CA[GB18030]**):
```
(;FF[4]GM[1]
CA[GB18030]
TE[2018ÀöË®ÇåÔÏ±­ÖÐ¹úÒµÓà¹«¿ªÈü2]
RD[2018-04-24]
PC[ÀöË®ÊÐËÉÑôÏØ]
TM[70]
LT[15]
LC[3]
KO[7.5]
RE[ºÚÊ¤2ÓÖ3/4×Ó]
```
This can now be opened by all SGF editors and GRP :)

[ls2018qy2-180424h_gb18030.sgf.zip](https://github.com/pnprog/goreviewpartner/files/2063129/ls2018qy2-180424h_gb18030.sgf.zip)

**Comment by l1t1** [comment]
thanks, it works
