### ISSUE TITLE
An unstandard SGF file: Error while reading komi value, please check:

### ISSUE THREAD

**Issue by jiangwuyou** [pnprog/goreviewpartner#71]
Suggest to masked Line 569 in toolbox.py

  #			show_error(_("Error while reading komi value, please check:")+"\n"+unicode(e),parent=self)
  #			komi_entry.insert(0, "0")
			komi_entry.insert(0, "7.5")  #Chinese rule

for common Go user.

**Comment by jiangwuyou** [comment]
(;SZ[19]
EV[分先:黑贴7目半]
DT[2018-05-02 20:46:58]
PW[徐嘉泽]
WR[1k]
PB[陈俊升]
BR[1k]
KM[]
RE[白胜43.5目];
B[pc];
W[pq];
B[dq];
W[dd];
B[jp];
W[pj];
B[jd];
W[dj];
B[cn];
W[gc];
B[qf];
W[mq];
B[qo];
W[qm];
B[oo];
W[qp];
B[mo];
W[po];
B[op];
W[pp];
B[lp];
W[oq];
B[np];
W[gq];
B[go];
W[iq];
B[jq];
W[eq];
B[ep];
W[fp];
B[eo];
W[er];
B[dr];
W[jr];
B[kr];
W[ir];
B[ip];
W[hp];
B[ho];
W[gp];
B[fo];
W[gr];
B[mc];
W[ic];
B[cf];
W[ce];
B[df];
W[cl];
B[ch];
W[ci];
B[dh];
W[qg];
B[pg];
W[qh];
B[ph];
W[pf];
B[pe];
W[of];
B[oe];
W[nh];
B[ng];
W[og];
B[oh];
W[nf];
B[oi];
W[qe];
B[rf];
W[re];
B[qi];
W[rg];
B[pi];
W[qc];
B[qb];
W[rc];
B[qd];
W[rd];
B[pd];
W[rb];
B[pb];
W[mg];
B[qj];
W[qk];
B[rk];
W[rl];
B[pk];
W[ql];
B[ok];
W[rj];
B[ri];
W[sk];
B[om];
W[jj];
B[jl];
W[il];
B[ik];
W[jk];
B[hk];
W[hl];
B[gl];
W[gk];
B[hm];
W[im];
B[jm];
W[in];
B[hj];
W[gj];
B[hi];
W[kn];
B[jn];
W[gm];
B[hn];
W[fl];
B[io];
W[gl];
B[gh];
W[gi];
B[hg];
W[ke];
B[kd];
W[ld];
B[lc];
W[le];
B[md];
W[ni];
B[nj];
W[mj];
B[mk];
W[lk];
B[ll];
W[ml];
B[nk];
W[li];
B[kk];
W[lj];
B[kj];
W[ki];
B[kl];
W[jh];
B[if];
W[jf];
B[ne];
W[me];
B[id];
W[hd];
B[he];
W[ge];
B[gf];
W[fe];
B[ff];
W[ee];
B[ef];
W[de];
B[fi];
W[fj];
B[ei];
W[ih];
B[hh];
W[dm];
B[dn];
W[en];
B[ai];
W[bj];
B[aj];
W[bl];
B[bk];
W[ck];
B[ak];
W[bh];
B[bg];
W[ah];
B[di];
W[bi];
B[ag];
W[al];
B[cm];
W[fn];
B[nq];
W[nr];
B[lr];
W[mr];
B[lq];
W[jc];
B[kc];
W[ig];
B[**];
W[ib];
B[kb];
W[cc];
B[pn];
W[qn];
B[pm];
W[qa];
B[pa];
W[ra];
B[je];
W[kg];
B[pl];
W[ao];
B[bp];
W[ap];
B[bq];
W[aq];
B[br];
W[ar];
B[bo];
W[an];
B[ad];
W[bb];
B[ac];
W[ab];
B[ia];
W[hb];
B[ha];
W[ga];
B[ja];
W[ae];
B[be];
W[bd];
B[af];
W[cg];
B[dg];
W[bc];
B[ae];
W[ls];
B[ks];
W[ms];
B[mp];
W[or];
B[sg];
W[sf];
B[sh];
W[rh];
B[si];
W[sj];
B[oj];
W[bm];
B[bn];
W[ds];
B[cs];
W[es];
B[js];
W[is];
B[ij];
W[ji];
B[ej];
W[ek];
B[ii];
W[gn];
B[bs];
W[am];
B[as];
B[as];
B[as];
)

**Comment by jiangwuyou** [comment]
Then will get:
LeelaZero started
LeelaZero identification through GTP...
LeelaZero identified itself properly
Checking version through GTP...
Version: 0.15
Setting goban size as 19x19
Clearing the board
Checking for existing stones or handicap stones on the board
The SGF does not indicate handicap stone

**Comment by jiangwuyou** [comment]
But 
self._property_map {'BR': ['1k'], 'CA': ['UTF-8'], 'DT': ['2018-05-02 20:46:58'], 'EV': ['\xe5\x88\x86\xe5\x8...5\x8d\x8a'], 'KM': ['7.5'], 'PB': ['\xe9\x99\x88\xe4\xb...5\x8d\x87'], 'PW': ['\xe5\xbe\x90\xe5\x9...6\xb3\xbd'], 'RE': ['\xe7\x99\xbd\xe8\x8...7\x9b\xae'], 'SZ': ['19'], 'WR': ['1k']}

So that there's no AB,AW,AE:(

**Comment by pnprog** [comment]
Hi!
There are 2 issues in this SGF files:

- Wrong komi value as you pointed out: `KM[]`
- There is one black move wrongly defined around move 251: `B[**];`:
```
B[kc];
W[ig];
B[**];
W[ib];
B[kb];
```
What move is supposed to be `B[**]` is is a pass move?

I can patch both of these, but I am curious to know where this nonstandard SGF comes from? It would be a good thing to alert the software authors about this behaviour.

**Comment by l1t1** [comment]
A valid SGF file for Go should start with ;FF[4]GM[1] as bellow:

(;FF[4]GM[1]   
#64

**Comment by jiangwuyou** [comment]
Yeah. I checked it through MultiGo. It parse B[**]; an B[A1], then ignore all move after that wrong move.

**Comment by jiangwuyou** [comment]
EV[分先:黑贴7目半] Chinese, means 7.5KM
KM[] Empty

**Comment by pnprog** [comment]
@jiangwuyou , do you have any idea where this SGF file comes from? or what software was used to register it?

**Comment by jiangwuyou** [comment]
Another GRP user asked a question in Chinese:
 He tested LeelaZero in GRP.
i7-8700+GTX1060+Win10   get  200 n/s :(
How to set the correct parameter in GRP.

**Comment by pnprog** [comment]
> I have sent one GRP user a message where he got that SGF file.

Good: if it is only one isolated SGF with this issue, we don't care. But if there is one software that many players use to generate nonstandard SGF, it's better to modify GRP to deal with them.

> i7-8700+GTX1060+Win10 get 200 n/s :(

I am not sure where is the problem? is 200 n/s too slow? If the latest LeelaZero is used, I would say 200 n/s is quite good already. I don't have answers, but here is a thread with users discussing LZ performance on different GPU, he can compare with his own GPU and ask for advice: [https://www.reddit.com/r/cbaduk/comments/8o87pr/gpu_and_how_many_visits_do_they_get/](https://www.reddit.com/r/cbaduk/comments/8o87pr/gpu_and_how_many_visits_do_they_get/)

At least he should try to adjust the number of thread and see how the number of n/s change: **--threads**

**Comment by pnprog** [comment]
Hi!
This is just to mention that I patched those two issues:

> - Wrong komi value as you pointed out: `KM[]`
> - There is one black move wrongly defined around move 251: `B[**];`:

I wanted to wait to understand how those files were generated, but I inadvertently pushed the modifications together with another commit :man_facepalming:

**Comment by jiangwuyou** [comment]
That reporter hasn't replied my question until now. Anyway, a patch is better since MultiGo can read that file.
