### ISSUE TITLE
Leela_zero_Goreviewpartner.ipynb is out of date

### ISSUE THREAD

**Issue by DavidKillen** [pnprog/goreviewpartner#74]
Transferred to lifein19x19

**Comment by pnprog** [comment]
Hi!

Issue Github's issues for questions is just fine (and I can't find the topic on L19 by the way).

Regarding the issue, I don't know about Colab or that project, but the error indicated by GRP (`Error while writting to stdin`) indicates an error while writing to LeelaZero's standard Input, not GRP's standard input.

The first thing GRP does after launching LeelaZero is to send the GTP commands `name` and `version` to ensure the correct program is running in GTP mode.

Failure to write to LeelaZero's stdin most probably means that LeelaZero crashed/terminated immediately after startup. You should check the command used for startup, and try to run it outside of GRP.

I never tried Colab, but I will see if I can have a try. From what I can understand, it should work for the newest or and older version of GRP.
