### ISSUE TITLE
Fails to open SGFs with UTF-8 characters in the filename on Windows

### ISSUE THREAD

**Issue by apetresc** [pnprog/goreviewpartner#84]
On Windows using the latest release of goreviewpartner, I attempted to open an SGF at the path: `X:\Games\Go\SGFs\apetresc\[apetresc]vs[云骐]1535082067010001217.sgf`. GRP fails with the following stack trace:
```
filename: X:/Games/Go/SGFs/apetresc/[apetresc]vs[??]1535082067010001217.sgf
Could not open the SGF file X:/Games/Go/SGFs/apetresc/[apetresc]vs[??]1535082067010001217.sgf
=> 22 invalid mode ('r') or filename
converting GRPException error message from unicode to str
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1532, in __call__
  File "main.py", line 109, in launch_analysis
  File "toolbox.pyc", line 438, in __init__
  File "toolbox.pyc", line 339, in open_sgf
GRPException: Could not open the RSGF file: X:/Games/Go/SGFs/apetresc/[apetresc]vs[Σ║æΘ¬É]1535082067010001217.sgf
invalid mode ('r') or filename
```

Renaming the file to something without UTF-8 characters, like just `X:\Games\Go\SGFs\apetresc\foxwq2.sgf` works fine, even though *the actual file contents* also contain the exact same UTF-8 characters. I assume that the presence of UTF-8 characters in the filename itself is what is causing the crash.

The following screenshot has all the relevant stuff happening all at once:
![image](https://user-images.githubusercontent.com/14872/44563921-7189f180-a72e-11e8-9df2-5a0a6f537dc8.png)

**Comment by pnprog** [comment]
Hi!

Thanks for the details report.

This is unfortunate to still have such issues with encoding, as a lot of effort was made earlier this year to have GRP work on all type of encoding. Apparently, there are still improvement to be made.

It's hard for me to fix this without being able to reproduce this, but I will try something anyway.

Just for information, your terminal encoding is apparently **cp437** that cannot display Asian characters, so the filename being displayed **[apetresc]vs[??]1535082067010001217.sgf** is normal. But the original filename and encoding should be preserved.

I will try something to work around this issue.

**Comment by pnprog** [comment]
Hi!
I made a quick change that should make it work now (https://github.com/pnprog/goreviewpartner/commit/23568d24098d44e489e39292ebae4257ce87e70d)
If you have the possibility, can you try to run the latest sources and check if it's working?

**Comment by apetresc** [comment]
@pnprog - sorry for the delay, I've been quite busy the last few weeks.

Yup, I can confirm that [23568d2](https://github.com/pnprog/goreviewpartner/commit/23568d24098d44e489e39292ebae4257ce87e70d) fixed the issue - I can load these files without any issue now :)
