### ISSUE TITLE
GRP fails to download files from OGS with GRPException

### ISSUE THREAD

**Issue by cleinias** [pnprog/goreviewpartner#97]
I am unable to download sgf files from OGS directly (saving to disk and then loading them works fine, so it's not a problem with the files themselves).

Here is the exception I am getting:
`Exception in Tkinter callback

Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1541, in __call__
        return self.func(*args) 
 File "..../goreviewpartner/toolbox.py", line 227, in get
    write_rsgf(filename,sgf)
  File "..../goreviewpartner/toolbox.py", line 272, in write_rsgf
    raise GRPException(_("Could not save the RSGF file: ")+filename+"\n"+unicode(e))
GRPException: Could not save the RSGF file: 16115080-067-cleinias-ilsan.sgf
'str' object has no attribute 'serialise'
`
Platform is Archlinux, GRP up to date from github

**Comment by pnprog** [comment]
Hi!
Thanks for reporting the issue. I just pushed a commit that (hopefully) should fix your problem.
Can you have a try again?

**Comment by cleinias** [comment]
Tested---it works fine now, thanks
